server:
  port: 8199
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  # h2 데이터베이스 연결
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:1521/bank;MODE=MySQL
    username: sa
    password:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(JmZN+qJ5Oncudgad52j2vy6vtTjOI2XHYla5iYxFoOmv2Rp7ot5Eq3uS9VNIGUIA7QaHVgMLsy46AdSNKPzaGSqmI9/IZG+qKQcdSaryjIPZjXwKFtfUjA==)
            client-secret: ENC(R8+bVFTI4eyspeihdv5rCfd3sYOrD0bZaXZqGHIUV+FPFgDMvFQ3+YWxf1MNQgqs)
            scope: profile, email
            redirect-uri: ENC(ehs1RULEdNLOnVvj3ntmEB9zE63NfHeQQoYelNhuP4w1tX8ugsDydPBgStlZ3HU9FAdEoab5s7o=)

  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    show-sql: true
  output:
    ansi:
      enabled: always
logging:
  #  pattern:
  #    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  level:
    '[com.example.banksample]': debug
    '[org.hibernate.type]': trace


### Open API (Swagger UI)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /**